# ssh setup script taken from https://gitlab.lnu.se/2dv013/content/examples/example-dockerized-web-application/-/blob/main/.gitlab-ci.yml
.before_script_ssh_setup: &before_script_ssh_setup
  # Ensure ssh-agent is installed and started, essential for managing SSH keys.
  # (Change apt-get to yum if using an RPM-based image)
  - command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )

  # Start the ssh-agent in the background.
  - eval $(ssh-agent -s)

  # Add the SSH private key stored in the SSH_PRIVATE_KEY variable to the ssh-agent.
  # Using 'tr' to remove carriage return characters for compatibility with ed25519 keys.
  # Reference: https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  # Create the .ssh directory and set the correct permissions.
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  # Use ssh-keyscan to add the remote server's SSH key to the known_hosts file.
  # This prevents SSH from prompting for approval of the remote server's key.
  - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

image: node:23.11.0-bookworm-slim

stages:
  - test
  - deploy

# Modified version of job taken from https://docs.gitlab.com/user/project/releases/release_cicd_examples/
prepare_job:
  image: alpine:3.21.3
  stage: .pre                                              # This stage must run before the release stage
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                             # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH             # Run this job when commits are pushed or merged to the default branch
  script:
    - apk add jq
    - echo "VERSION=$(cat package.json | jq -r .version)" >> variables.env             # and append to the variables.env file
  artifacts:
    reports:
      dotenv: variables.env 

unit-test-job:
  stage: test
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Running unit tests..."
    - npm test

# Modified version of job taken from https://docs.gitlab.com/user/project/releases/release_cicd_examples/
release-job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: deploy
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "Creating release..."
  release:
    name: $VERSION
    description: "Release $VERSION"
    tag_name: $VERSION

deploy-job:
  image: docker:28.1.1-cli
  stage: deploy
  environment:
    name: production
    url: https://$PRODUCTION_HOST
  variables:
    DOCKER_HOST: ssh://ubuntu@$REMOTE_HOST
  before_script: 
    - *before_script_ssh_setup
  script:
    - echo "Deploying application..."
    - docker compose -f docker-compose.prod.yml up -d --build
  only:
    - main

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml