networks:
  geocreatornet:

services:
  mongodb:
    container_name: geocreator_mongodb
    image: mongo:latest
    volumes:
      - ./.volumes/mongodb:/data/db
    restart: unless-stopped

  geocreator:
    container_name: geocreator_prod
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/geocreator"
      PORT: "80"
      NODE_ENV: "production"
    restart: unless-stopped