networks:
  geocreatornet:

services:
  mongodb:
    container_name: geocreator_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/mongodb:/data/db
    restart: unless-stopped

  geocreator:
    container_name: geocreator_prod
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/geocreator"
      PORT: "80"
      NODE_ENV: "production"
      BASE_URL: $BASE_URL
      SESSION_NAME: $SESSION_NAME
      SESSION_SECRET: $SESSION_SECRET
    restart: unless-stopped