import "bootstrap";
import "leaflet";
import "./components/geocreator-map/index.js";
import "./components/geocreator-timer/index.js";
import "./components/my-alert/my-alert.js";
import "./config/cookie-consent.js";
import "./gameView.js";
import "./editForm.js";
import "./editLocation.js";
